# Generated by Django 2.0.3 on 2018-05-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20180528_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='purchasecomment',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='salecomment',
            old_name='userId',
            new_name='user',
        ),
    ]
