# Generated by Django 2.0.3 on 2018-05-30 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0003_auto_20180528_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_purchase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasecomment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_comments', to='transaction.Purchase'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salecomment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_comments', to='transaction.Sale'),
        ),
        migrations.AddField(
            model_name='saleinterest',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_interest', to='transaction.Sale'),
        ),
        migrations.AddField(
            model_name='saleinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_interest_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='saleinterest',
            unique_together={('user', 'sale')},
        ),
    ]
