# Generated by Django 2.0.3 on 2018-06-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20180531_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='author',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bookTitle',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='author',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bookTitle',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
    ]
