# Generated by Django 2.0.3 on 2018-06-04 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20180604_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='content',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='sale',
            name='content',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
