# Generated by Django 2.0.3 on 2018-06-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20180604_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='author',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bookTitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='content',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='publisher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='author',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bookTitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='content',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='sale',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='publisher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
