# Generated by Django 2.0.3 on 2018-06-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20180604_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
