# Generated by Django 2.0.3 on 2018-06-04 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20180604_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
