# Generated by Django 2.0.3 on 2018-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmationToken',
            field=models.CharField(default='', max_length=100),
        ),
    ]
